name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Restore cached npm dependencies
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: npm-dependencies-${{ hashFiles('yarn.lock') }}

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile

      - name: Cache npm dependencies
        uses: actions/cache/save@v4
        with:
          path: node_modules
          key: npm-dependencies-${{ hashFiles('yarn.lock') }}

      - uses: nrwl/nx-set-shas@v4
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main
      - run: yarn nx affected -t lint test --parallel=3
      - run: yarn nx affected -t build --parallel=3
