name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

permissions:
  # needed for nrwl/nx-set-shas@v4 to work on main branch (https://github.com/nrwl/nx-set-shas/issues/89#issuecomment-1519178667)
  contents: read
  actions: read
  # needed for azure cli
  id-token: write

jobs:
  prepare:
    name: 'Prepare'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Put me back to subscription
        run: az role assignment create --assignee joaoantunes87@gmail.com --role Owner --scope /subscriptions/4af25709-ced6-430c-aa21-346a9491144e
