name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    # needed for nrwl/nx-set-shas@v4 to work on main branch
    permissions:
      contents: read
      actions: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Restore cached npm dependencies
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: npm-dependencies-${{ hashFiles('yarn.lock') }}

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile

      - name: Cache npm dependencies
        uses: actions/cache/save@v4
        with:
          path: node_modules
          key: npm-dependencies-${{ hashFiles('yarn.lock') }}

      - name: Derive NX_BASE and NX_HEAD for Affected
        uses: nrwl/nx-set-shas@v4

      # This line is needed for nx affected to work when CI is running on a PR
      - name: Affected for PR
        if: ${{contains(github.ref, 'refs/pull/')}}
        run: git branch --track main origin/main

      - name: Lint and test affected projects
        run: yarn nx affected -t lint test --parallel=3

      - name: Build affected projects
        run: yarn nx affected -t build --parallel=3

      - name: Sets Azure environment production for deploy when in main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "AZURE_ENVIRONMENT=production" >> $GITHUB_ENV

      - name: Deploy affected apps to Azure
        env:
          AZURE_TOKEN_APP_ONE: ${{ secrets.AZURE_TOKEN_APP_ONE }}
          AZURE_TOKEN_APP_TWO: ${{ secrets.AZURE_TOKEN_APP_TWO }}
        run: yarn nx affected -t deploy-azure --parallel=1

      - name: Deploy affected apps to Firebase for main
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          FIREBASE_TOKEN: ${{ secrets.firebaseToken }}
          FIREBASE_PROJECT_APP_ONE: ${{ secrets.firebaseProjectAppOne }}
          FIREBASE_PROJECT_APP_TWO: ${{ secrets.firebaseProjectAppTwo }}
        run: yarn nx affected -t deploy --parallel=3
