on:
  pull_request:
    types: [closed]

jobs:
  close:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Closed merge request
        run: echo "merge request closed: $GITHUB_HEAD_REF"
