name: PR Cleanup
on:
  pull_request:
    # types: [closed]

jobs:
  close:
    runs-on: ubuntu-latest

    steps:
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az account show
            az storage -h
